### ISSUE TITLE
Chess pieces don't show up

### ISSUE THREAD

**Issue by velikanov** [fulldecent/FDChessboardView#16]
Hi everyone!
I've imported FDChessboardView via CocoaPods (from git master) and copied datasource  from Example
But no chess pieces have shown up, only board.
I tried to debug and it looks like that chess pieces are being created, but not being drawn.
What am I doing wrong?

One thing that I have noticed is that master branch has SVG images, but in XCode I see PNG images… Maybe that's the case…

**Comment by fulldecent** [comment]
Hmm, is that the 2.0 release?

Has anybody else here seen this problem?

**Comment by velikanov** [comment]
yup, I just added it to Podfile as a git repository
one more thing - Example project does work and shows all pieces fine…
It's my own issue for sure, but I don't understand what I'm doing wrong

**Comment by fulldecent** [comment]
We just made a major release, now using Swift Package Manager. Could you please retry to see if this fixed it?

Please reopen if this is still not working for you.
